pull_request_rules:
  - name: automatic merge if label exists and build passes
    conditions:
      - status-success=build
      - label=auto-merge
    actions:
      merge:
        method: merge
      comment:
        message: Auto merged after build passed and auto-merge label detected
      label:
        remove: auto-merge
