name: CI

# on: [push, pull_request]
on:
  push:
    branches-ignore:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: functions/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: |
          cd functions
          npm install

      - name: Build
        run: |
          cd functions
          npm run-script build
