name: Deployment

on:
  pull_request:
    branches: develop
    types: [closed]

jobs:
  deploy:
    name: Deploy Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: functions/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy -P default --only firestore,storage,functions,hosting:develop-docs
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
