name: Firebase

on:
  pull_request:
    branches: develop
    types: [closed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
